[project]
name = "referentiel-sync"
version = "0.1"
dependencies = [
    "awscli==1.25.56",
    "python-decouple==3.6",
    "sentry-sdk==1.14.0",
    "tenacity==8.2.2",
    "watchdog==2.1.9",
]

[tool.setuptools]
packages = []
