[project]
name = "trackdechets-vigiedechets"
version = "0.1.0"
description = "MTE VigiedÃ©chets"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery==5.5.3",
    "clickhouse-sqlalchemy>=0.2.3",
    "django>=5.2.8",
    "django-admin-rangefilter>=0.13.3",
    "django-anymail[sendinblue]>=13.1",
    "django-braces>=1.17.0",
    "django-defender>=0.9.8",
    "django-environ>=0.12.0",
    "django-filter>=25.2",
    "django-grappelli>=4.0.2",
    "django-import-export[xlsx]>=4.3.13",
    "django-jsonform>=2.23.2",
    "django-mptt>=0.18.0",
    "django-otp>=1.6.3",
    "django-prose-editor[sanitize]>=0.21.0",
    "django-registration>=5.2.1",
    "django-simple-menu>=2.1.4",
    "django-solo>=2.4.0",
    "django-storages[s3]>=1.14.6",
    "django-template-partials>=25.2",
    "django-vite>=3.1.0",
    "djangorestframework>=3.16.1",
    "geopandas==1.1.1",
    "gunicorn>=23.0.0",
    "icalendar==6.3.1",
    "httpx>=0.28.1",
    "kaleido==0.2.1",
    "mozilla-django-oidc>=4.0.1",
    "numpy==2.3.5",
    "pandas==2.3.3",
    "paramiko<5",
    "plotly==6.5.0",
    "polars==1.35.2",
    "psycopg2-binary>=2.9.11",
    "pyarrow==22.0.0",
    "redis==7.0.1",
    "sentry-sdk[django]>=2.43.0",
    "sqlalchemy==2.0.44",
    "sshtunnel==0.4.0",
    "weasyprint==66.0",
    "whitenoise>=6.11.0",
    "xlsxwriter>=3.2.9",
    "django-htmx>=1.26.0",
    "django-multiupload>=0.6.1",
    "pandera>=0.29.0",
]

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "djade>=1.6.0",
    "django-debug-toolbar<6",
    "django-extensions>=4.1",
    "isort>=7.0.0",
    "mypy>=1.18.2",
    "pywatchman",
    "ruff>=0.14.3",
]
test = [
    "pytest",
    "pytest-django",
    "pytest-cov",
    "factory-boy",
]

[tool.ruff]
target-version = "py311"
line-length = 119
extend-exclude = ["migrations"]
[tool.bandit]
exclude_dirs = ["tests", "/config/settings/dev.py"]
