version: '3'

services:
  mss-journal-db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - mss-network
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.51.3
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=mss-journal
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      - MB_DB_HOST=mss-journal-db
    networks:
      - mss-network
    ports:
      - "3001:3000"
    depends_on:
      - mss-journal-db

  # https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
  node:
    image: node:22
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm ci && ./node_modules/.bin/knex migrate:latest"
    networks:
      - mss-network
    depends_on:
      - mss-journal-db

networks:
  mss-network:
    external: true
