[project]
name = "trackdechets-assistance"
version = "0.1.0"
description = "TrackdÃ©chets website and assistance"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "django-environ>=0.12.0",
    "django-admin-sortable2>=2.2.8",
    "markdown==3.9",
    "django-mptt==0.18.0",
    "django-grappelli==4.0.2",
    "martor==1.7.15",
    "django-widget-tweaks==1.5.0",
    "django-multiupload==0.6.1",
    "django-request==1.7.0",
    "icalendar==6.3.1",
    "django-ical==1.9.2",
    "django-hosts==7.0.0",
    "djangorestframework==3.16.1",
    "django-cors-headers==4.9.0",
    "httpx==0.28.1",
    "django-template-partials==25.2",
    "sib-api-v3-sdk==7.6.0",
    "django-compressor==4.5.1",
    "django-permissions-policy==4.28.0",
    "sentry-sdk[django]>=2.43.0",
    "django-csp==4.0",
    "dnspython==2.8.0",
    "django-solo==2.4.0",
    "whitenoise==6.11.0",
    "psycopg2-binary>=2.9.11",
    "gunicorn>=23.0.0",
]

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "djade>=1.6.0",
    "django-debug-toolbar<6",
    "django-extensions>=4.1",
    "isort>=7.0.0",
    "mypy>=1.18.2",
    "pywatchman",
    "ruff>=0.14.3",
]
test = [
    "pytest",
    "pytest-django",
    "pytest-cov",
    "factory-boy",
]
[tool.ruff]
target-version = "py313"
line-length = 119
extend-exclude = ["migrations"]
[tool.bandit]
exclude_dirs = ["tests", "/config/settings/dev.py"]
