[project]
name = "evalap"
version = "0.3.0"
description = "Evaluations API and Platform"
authors = [{ name = "Etalab", email = "etalab@modernisation.gouv.fr" }]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }
keywords = ["IA", "LLM", "evaluation"]

dependencies = [
    # API
    "fastapi~=0.115.2",
    "SQLAlchemy~=2.0.35",
    "sqlalchemy-utils~=0.41.2",
    "alembic~=1.13.3",
    "uvicorn~=0.32.0",
    "requests~=2.32.3",
    "python-dotenv~=1.1.1",
    "psycopg2-binary~=2.9.10",
    "pandas~=2.2.3",
    "pyzmq~=26.2.0",
    "jinja2~=3.1.4",
    "pydantic~=2.11.9",
    "inflection~=0.5.1",
    "docopt-ng~=0.9.0",
    "pillow~=11.1.0",
    "aiofiles~=24.1.0",
    "pyarrow~=19.0.1",
    "deepeval~=3.5.1",
    "ragas~=0.2.14",
    "rapidfuzz~=3.13.0",
    "ecologits~=0.6.2",
    "toml~=0.10.2",
    "supervisor~=4.2.5",
    "tqdm~=4.67.1",
    "elasticsearch~=9.2.0",
    # Front
    "streamlit~=1.40.1",
    "plotly~=5.22.0",
    "openpyxl~=3.1.5",
    "huggingface-hub>=1.2.3",
    "tabulate~=0.9.0",
]

[project.urls]
Homepage = "https://evalap.etalab.gouv.fr"
Source = "https://github.com/etalab-ia/evalap"
Tracker = "https://github.com/etalab-ia/evalap/issues"
Documentation = "https://github.com/etalab-ia/evalap"

[project.scripts]
evalap_generate_answers = "evalap.scripts.run_answers.run_answers:main"
evalap_run_expe = "evalap.scripts.run_expe.run_expe:main"

# Tests

[project.optional-dependencies]
test = [
    "pytest==8.3.3",
    "pytest-asyncio==0.24.0",
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests/"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]


# Packaging

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {where = ["."], include = ["evalap*"]}}
include-package-data = true

[tool.setuptools.package-data]
evalap_config = ["config/*"]

[tool.pdm]
distribution = false

# Linter

[tool.ruff]
line-length = 111
exclude = ["evalap/api/alembic/versions/", "notebooks/", ".claude/", ".cursor/", ".specify/", ".windsurf/"]

[tool.ruff.lint]
select = [
    "F",    # Pyflakes (includes undefined variables)
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "Q",    # flake8-quotes (quote style consistency)
    "B",    # flake8-bugbear (likely bugs and design problems)
    "I",    # isort
]
fixable = ["ALL"]
unfixable = []
ignore = [
    "E711", # Disable E711 specifically to prevent issues with SQLAlchemy
    #"F403", # import *
    #"F841", # never used variables
]

[tool.ruff.lint.isort]
known-third-party = ["alembic"]
known-first-party = ["api", "config", "tests", "ui"]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.13.0",
    "pytest-cov>=7.0.0",
    "ipykernel>=6.30.1",
    "watchdog>=6.0.0",
]
