[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/dist
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "E266", "E701", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "dist",
    "*.egg-info",
    ".yarn",
    "node_modules",
    "venv",
    ".venv"
]
per-file-ignores = [
    "backend/settings/local.py:F405"
]

[tool.pytest.ini_options]
addopts = "--ds=backend.settings.test --reuse-db --no-migrations"
testpaths = ["backend"]