services:
  postgres:
    image: postgres:16.5
    restart: always
    user: postgres
    environment:
      - TZ=Europe/Paris
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=evalap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 4s
      timeout: 10s
      retries: 5
      start_period: 60s

  evalap:
    image: ghcr.io/etalab-ia/evalap/evalap:main-latest
    restart: always
    environment:
      - TZ=Europe/Paris
      - ENV=prod
      - DB_NAME=${DB_NAME:-evalap}
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://postgres:postgres_password@postgres:5432/evalap}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - HF_TOKEN=${HF_TOKEN}
      - MFS_API_KEY_V2=${MFS_API_KEY_V2}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - ALBERT_API_KEY=${ALBERT_API_KEY}
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - evalap_data:/data
      - huggingface_cache:/root/.cache/huggingface
    command: ["supervisord", "-c", "/app/supervisord.conf"]
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres_data:
  evalap_data:
  huggingface_cache:
