[tool.poetry]
name = "2ddoc_parser"
version = "1.0.3"
description = "Api pour décodé et vérifier les 2D docs de l'ANTS"
authors = ["Nicolas Sagon <nicolas.sagon@beta.gouv.fr>"]
readme = "README.md"
license = "MIT"
packages = [
    { include = "fr_2ddoc_parser", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.13"
cryptography = "^43.0.0"
typing-extensions = "^4.12.2"
pydantic = "^2.12.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.11"
pytest = "^8.4.1"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
