[project]
name = "suggestions2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.7,<0.116.0",
    "numpy>=2.3.0",
    "pandas>=2.2.3",
    "prometheus-client==0.21.1",
    "psycopg==3.2.4",
    "python-dotenv==1.0.1",
]

[dependency-groups]
dev = ["pytest>=8.4.1"]

[tool.ruff]
line-length = 88
indent-width = 4
