[project]
name = "portail-rse-esg-api"
version = "0.1.0"
description = "API connectÃ©e au moteur IA"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beevibe==0.1.0",
    "celery>=5.4.0",
    "click>=8.1.8",
    "flask-jwt-extended>=4.7.1",
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "honcho>=2.0.0",
    "joblib>=1.4.2",
    "pandas>=2.2.3",
    "pymupdf==1.25.3",
    "python-dotenv>=1.0.1",
    "redis>=5.2.1",
]

[dependency-groups]
dev = [
    "flasgger>=0.9.7.1",
    "flower>=2.0.1",
    "jupyterlab>=4.3.5",
    "ruff>=0.9.8",
]
