[tool.poetry]
name = "document-ia-infra"
version = "0.1.2"
description = "Code des briques d'infrastructure pour Document IA"
authors = ["Nicolas Sagon <nicolas.sagon@beta.gouv.fr>"]
readme = "README.md"
packages = [
    { include = "document_ia_infra", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.0.0"
redis = "^5.0.0"
boto3 = "1.35.99"
pydantic = "^2.11.9"
openai = "^1.108.1"
tiktoken = "^0.11.0"
sqlalchemy = "^2.0.43"
asyncpg = "^0.30.0"
mypy-boto3-s3 = "^1.40.26"
python-logging-loki = "^0.3.1"
document-ia-schemas = { path = "../document-ia-schemas", develop = false }
cryptography = "^43.0.0"
psycopg2-binary = "^2.9.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.11"
pytest = "^8.4.1"
pytest-asyncio = "^0.23.0"
pydantic-settings = "^2.1.0"
pre-commit = "^3.6.0"
pyright = "^1.1.405"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
asyncio_mode = "auto"
