version: '3'

services:
  st-projets:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - user-avatars:/app/public/user-avatars
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres@postgres/projets
      - SECRET_KEY=notsecretkey
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=projets
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d projets']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-avatars:
  attachments:
  db-data:
