[project]
name = "cron-grist-to-brevo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.2.9",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
]

[tool.black]
