[project]
name = "{{ project_name }}"
version = "0.11.1" # x-release-please-version
description = "{{ description }}"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "albert-client",
    "pipelines",
    "rag-core",
    "python-dotenv>=1.0.0",
    "reflex>=0.7.11",
]

[project.scripts]
reflex-chat = "reflex.reflex:cli"

[tool.setuptools.packages.find]
include = ["{{ project_name | replace(from='-', to='_') }}*"]

[tool.uv.sources]
albert-client = { workspace = true }
pipelines = { workspace = true }
rag-core = { workspace = true }

[tool.uv]
package = true
