[project]
name = "rag-facile"
version = "0.1.0"
description = "RAG Starter Kit for French Government"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "chainlit-chat",
    "admin",
    "ingestion",
    "cli",
    "pdf-context",
    "reflex-chat",
]

[tool.uv.sources]
chainlit-chat = { workspace = true }
admin = { workspace = true }
ingestion = { workspace = true }
cli = { workspace = true }
pdf-context = { workspace = true }
reflex-chat = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.14.14",
    "ty>=0.0.1",
    "pre-commit>=4.0.1",
]

[tool.uv.workspace]
members = ["apps/*", "packages/*"]
