services:
  dbreva:
    image: postgres:16.11
    container_name: postgresql_reva
    restart: always
    environment:
      POSTGRES_DB: reva
      POSTGRES_USER: reva
      POSTGRES_PASSWORD: password
    ports:
      - 5444:5432
