services:
  web:
    build: .
    image: espacemembre-ruby
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:dummy@db:5434
    volumes:
      - "./:/app"
      - "/app/node_modules"
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - "./tmp/primarydb:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 'dummy'
      PGPORT: 5434
